### ISSUE TITLE
针对Button，如果在同一主题下面，Button有多个背景颜色，如何设计？

### ISSUE THREAD

**Issue by huangzhifei** [JyHu/Chameleon#1]
仔细看了作者写的文章，写得很好，不知道对于同一主题下面同一个抽象控件（比如UIButton）有多个背景颜色，及在不同背景颜色下面有不同的字体大小和字体颜色，该如何设计，才能让使用者做到见名知义了？

思考：

想过参考UIButton的构造方法中枚举一样（UIButtonTypeCustom和UIButtonTypeSystem等）在Button这个json文件下面设置对应的key和value，但是如果在同一个主题下面button超过3种以上的不同背景颜色，使用者可能需要通过看注释说明，如果在添加一个新的主题，json文件中的颜色值对应关系也不好确定。

**Comment by JyHu** [comment]
封装一个换肤的框架肯定是面向于所有基本场景的，对于你说的这种属于高定制化的需求了，跟业务有高耦合性，可以看下  UINavigationBar+APPAppearance  这个类里面，对于 UINavigationBar来说，是没有直接设置title颜色的属性的，需要设置titleTextAttributes这个属性，那我就可以自己写一个app_titleColor属性，在换肤的时候执行到我自己自定义的方法中，拿到换肤的属性后在自定义的方法内做自己自定义的处理。
像你说的一个button有不同的皮肤属性，完全可以自定义一个方法比如 setBackGroundColor:forControlState:withType 等，方法定义好就行。

**Comment by JyHu** [comment]
> 仔细看了作者写的文章，写得很好，不知道对于同一主题下面同一个抽象控件（比如UIButton）有多个背景颜色，及在不同背景颜色下面有不同的字体大小和字体颜色，该如何设计，才能让使用者做到见名知义了？
> 
> 思考：
> 
> 想过参考UIButton的构造方法中枚举一样（UIButtonTypeCustom和UIButtonTypeSystem等）在Button这个json文件下面设置对应的key和value，但是如果在同一个主题下面button超过3种以上的不同背景颜色，使用者可能需要通过看注释说明，如果在添加一个新的主题，json文件中的颜色值对应关系也不好确定。

**Comment by huangzhifei** [comment]
目前方案基本也是通过type来初始化，内部做好主题管理，隐藏细节

发自我的 iPhone
